---
name: Sourcegraph Go SCIP Indexer
description: Generate SCIP data from Go source code
author: Sourcegraph
branding:
  icon: code
  color: orange

inputs:
  github-token:
    description: GitHub access token with 'public_repo' scope for repository verification when lsif.enforceAuth is enabled
    required: false
  go-mod-name:
    description: Specifies the name of the module defined by go-mod-root
    required: false
  go-mod-root:
    description: Specifies the directory containing the go.mod file
    required: false
  go-mod-version:
    description: Specifies the version of the module defined by go-mod-root
    required: false
  output:
    description: Output file path for the SCIP index
    default: index.scip
  package-patterns:
    description: "Package patterns to index. Default: './...' indexes all packages recursively."
    default: "./..."
  project-root:
    description: Specifies the directory to index
    default: .
  quiet:
    description: Do not output to stdout or stderr
    default: "false"
  repository-remote:
    description: Specifies the canonical name of the repository remote
    required: false
  repository-root:
    description: Specifies the top-level directory of the git repository
    required: false
  scip-go-version:
    description: Version of scip-go to use (e.g., "v0.1.26", "latest")
    default: "v0.1.26"
  skip-implementations:
    description: Skip generating implementations
    default: "false"
  skip-tests:
    description: Skip compiling tests. Will not generate SCIP indexes over tests.
    default: "false"
  sourcegraph-token:
    description: Sourcegraph access token for uploading indexes
    required: false
  sourcegraph-url:
    description: URL of the Sourcegraph instance (e.g., https://sourcegraph.com)
    required: false
  src-cli-version:
    description: Version of src-cli to use for uploads (e.g., "6.12.0", "latest")
    default: "6.12.0"
  upload:
    description: Upload the index to a Sourcegraph instance
    default: "false"
  verbose:
    description: Verbosity level (0=default, 1=verbose, 2=very verbose, 3=very very verbose)
    default: "0"

outputs:
  index-path:
    description: Path to the generated SCIP index file
    value: ${{ steps.scip-go.outputs.index-path }}

runs:
  using: composite
  steps:
    - name: Install scip-go
      shell: bash
      env:
        SCIP_GO_VERSION: ${{ inputs.scip-go-version }}
      run: |
        set -euo pipefail
        echo "Installing scip-go@${SCIP_GO_VERSION}..."
        go install "github.com/sourcegraph/scip-go/cmd/scip-go@${SCIP_GO_VERSION}"
        echo "scip-go installed successfully"
        scip-go --version || true

    - name: Run scip-go
      id: scip-go
      shell: bash
      working-directory: ${{ inputs.project-root }}
      env:
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_MODULE_ROOT: ${{ inputs.go-mod-root }}
        INPUT_REPOSITORY_ROOT: ${{ inputs.repository-root }}
        INPUT_REPOSITORY_REMOTE: ${{ inputs.repository-remote }}
        INPUT_MODULE_NAME: ${{ inputs.go-mod-name }}
        INPUT_MODULE_VERSION: ${{ inputs.go-mod-version }}
        INPUT_QUIET: ${{ inputs.quiet }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        INPUT_SKIP_IMPLEMENTATIONS: ${{ inputs.skip-implementations }}
        INPUT_SKIP_TESTS: ${{ inputs.skip-tests }}
        INPUT_PACKAGE_PATTERNS: ${{ inputs.package-patterns }}
        INPUT_PROJECT_ROOT: ${{ inputs.project-root }}
      run: |
        set -euo pipefail

        ARGS=()
        if [ -n "$INPUT_OUTPUT" ]; then
          ARGS+=("--output=$INPUT_OUTPUT")
        fi
        if [ -n "$INPUT_MODULE_ROOT" ]; then
          ARGS+=("--go-mod-root=$INPUT_MODULE_ROOT")
        fi
        if [ -n "$INPUT_REPOSITORY_ROOT" ]; then
          ARGS+=("--repository-root=$INPUT_REPOSITORY_ROOT")
        fi
        if [ -n "$INPUT_REPOSITORY_REMOTE" ]; then
          ARGS+=("--repository-remote=$INPUT_REPOSITORY_REMOTE")
        fi
        if [ -n "$INPUT_MODULE_NAME" ]; then
          ARGS+=("--go-mod-name=$INPUT_MODULE_NAME")
        fi
        if [ -n "$INPUT_MODULE_VERSION" ]; then
          ARGS+=("--go-mod-version=$INPUT_MODULE_VERSION")
        fi
        if [ "$INPUT_QUIET" = "true" ]; then
          ARGS+=("--quiet")
        fi
        if [ "$INPUT_VERBOSE" != "0" ]; then
          i=0
          while [ "$i" -lt "$INPUT_VERBOSE" ]; do
            ARGS+=("-v")
            i=$((i + 1))
          done
        fi
        if [ "$INPUT_SKIP_IMPLEMENTATIONS" = "true" ]; then
          ARGS+=("--skip-implementations")
        fi
        if [ "$INPUT_SKIP_TESTS" = "true" ]; then
          ARGS+=("--skip-tests")
        fi

        echo "Running: scip-go ${ARGS[*]} $INPUT_PACKAGE_PATTERNS"
        scip-go "${ARGS[@]}" "$INPUT_PACKAGE_PATTERNS"

        if [ -f "$INPUT_OUTPUT" ]; then
          echo "SCIP index generated successfully: $INPUT_OUTPUT"
          {
            echo "index-path<<EOF"
            echo "${INPUT_PROJECT_ROOT}/${INPUT_OUTPUT}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        else
          echo "::error::SCIP index file not found at $INPUT_OUTPUT"
          exit 1
        fi

    - name: Validate upload inputs
      if: inputs.upload == 'true'
      shell: bash
      env:
        SRC_ENDPOINT: ${{ inputs.sourcegraph-url }}
        SRC_ACCESS_TOKEN: ${{ inputs.sourcegraph-token }}
      run: |
        set -euo pipefail
        if [ -z "$SRC_ENDPOINT" ]; then
          echo "::error::sourcegraph_url is required when upload is enabled"
          exit 1
        fi
        if [ -z "$SRC_ACCESS_TOKEN" ]; then
          echo "::error::sourcegraph_token is required when upload is enabled"
          exit 1
        fi

    - name: Install src-cli
      if: inputs.upload == 'true'
      shell: bash
      env:
        SRC_CLI_VERSION: ${{ inputs.src-cli-version }}
      run: |
        set -euo pipefail
        mkdir -p "$HOME/.local/bin"

        case "$(uname -s)-$(uname -m)" in
          Linux-x86_64)  BINARY="src_linux_amd64" ;;
          Linux-aarch64) BINARY="src_linux_arm64" ;;
          Darwin-x86_64) BINARY="src_darwin_amd64" ;;
          Darwin-arm64)  BINARY="src_darwin_arm64" ;;
          *) echo "::error::Unsupported platform $(uname -s)-$(uname -m)"; exit 1 ;;
        esac

        if [ "$SRC_CLI_VERSION" = "latest" ]; then
          echo "Installing latest src-cli ($BINARY)..."
          echo "Warning: Checksum verification not available for 'latest' version"
          curl -fsSL "https://sourcegraph.com/.api/src-cli/$BINARY" -o "$HOME/.local/bin/src"
        else
          echo "Installing src-cli@${SRC_CLI_VERSION} ($BINARY)..."
          RELEASE_URL="https://github.com/sourcegraph/src-cli/releases/download/${SRC_CLI_VERSION}"
          curl -fsSL "${RELEASE_URL}/$BINARY" -o "$HOME/.local/bin/src"

          echo "Verifying checksum..."
          CHECKSUMS_FILE=$(mktemp)
          curl -fsSL "${RELEASE_URL}/src-cli_${SRC_CLI_VERSION}_checksums.txt" -o "$CHECKSUMS_FILE"

          EXPECTED_CHECKSUM=$(grep "  ${BINARY}\$" "$CHECKSUMS_FILE" | awk '{print $1}')
          if [ -z "$EXPECTED_CHECKSUM" ]; then
            echo "::error::Could not find checksum for $BINARY in checksums file"
            rm -f "$CHECKSUMS_FILE"
            exit 1
          fi

          if command -v sha256sum &> /dev/null; then
            ACTUAL_CHECKSUM=$(sha256sum "$HOME/.local/bin/src" | awk '{print $1}')
          else
            ACTUAL_CHECKSUM=$(shasum -a 256 "$HOME/.local/bin/src" | awk '{print $1}')
          fi

          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
            echo "::error::Checksum verification failed. Expected: $EXPECTED_CHECKSUM, Actual: $ACTUAL_CHECKSUM"
            rm -f "$CHECKSUMS_FILE" "$HOME/.local/bin/src"
            exit 1
          fi

          echo "Checksum verified successfully"
          rm -f "$CHECKSUMS_FILE"
        fi
        chmod +x "$HOME/.local/bin/src"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Upload SCIP index
      if: inputs.upload == 'true'
      shell: bash
      working-directory: ${{ inputs.project-root }}
      env:
        SRC_ENDPOINT: ${{ inputs.sourcegraph-url }}
        SRC_ACCESS_TOKEN: ${{ inputs.sourcegraph-token }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_REPOSITORY_REMOTE: ${{ inputs.repository-remote }}
        INPUT_PROJECT_ROOT: ${{ inputs.project-root }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -euo pipefail

        # Mask secrets to prevent accidental exposure in logs
        if [ -n "$SRC_ACCESS_TOKEN" ]; then
          echo "::add-mask::$SRC_ACCESS_TOKEN"
        fi
        if [ -n "$INPUT_GITHUB_TOKEN" ]; then
          echo "::add-mask::$INPUT_GITHUB_TOKEN"
        fi

        # Validate URL to prevent credential exfiltration
        if [[ ! "$SRC_ENDPOINT" =~ ^https:// ]]; then
          echo "::error::sourcegraph_url must use HTTPS"
          exit 1
        fi
        if [[ "$SRC_ENDPOINT" =~ @ ]]; then
          echo "::error::sourcegraph_url must not contain embedded credentials"
          exit 1
        fi

        UPLOAD_ARGS=("-file=$INPUT_OUTPUT" "-no-progress" "-json")

        if [ -n "$GITHUB_SHA" ]; then
          UPLOAD_ARGS+=("-commit=$GITHUB_SHA")
        fi

        if [ -n "$INPUT_REPOSITORY_REMOTE" ]; then
          UPLOAD_ARGS+=("-repo=$INPUT_REPOSITORY_REMOTE")
        elif [ -n "$GITHUB_REPOSITORY" ]; then
          UPLOAD_ARGS+=("-repo=github.com/$GITHUB_REPOSITORY")
        fi

        if [ -n "$INPUT_PROJECT_ROOT" ] && [ "$INPUT_PROJECT_ROOT" != "." ]; then
          UPLOAD_ARGS+=("-root=$INPUT_PROJECT_ROOT")
        fi

        if [ -n "$INPUT_GITHUB_TOKEN" ]; then
          UPLOAD_ARGS+=("-github-token=$INPUT_GITHUB_TOKEN")
        fi

        echo "Uploading SCIP index to $SRC_ENDPOINT..."
        echo "Running: src code-intel upload -file=$INPUT_OUTPUT -no-progress [additional flags...]"

        # Disable command tracing to prevent token exposure if set -x is enabled
        { set +x; } 2>/dev/null || true
        upload_output=$(src code-intel upload "${UPLOAD_ARGS[@]}" 2>&1) || upload_status=$?
        upload_status=${upload_status:-0}

        # Clear sensitive variables
        unset SRC_ACCESS_TOKEN INPUT_GITHUB_TOKEN

        # Display output to logs
        echo "$upload_output"

        if [ $upload_status -ne 0 ]; then
          echo "::error::Upload failed"
          exit $upload_status
        fi

        # Parse JSON output for job summary
        upload_repo=$(echo "$upload_output" | jq -r '.repo')
        upload_commit=$(echo "$upload_output" | jq -r '.commit')
        upload_root=$(echo "$upload_output" | jq -r '.root')
        upload_file=$(echo "$upload_output" | jq -r '.file')
        upload_indexer=$(echo "$upload_output" | jq -r '.indexer')
        upload_indexer_version=$(echo "$upload_output" | jq -r '.indexerVersion')
        upload_url=$(echo "$upload_output" | jq -r '.uploadUrl')

        {
          echo "### SCIP Index Upload"
          echo ""
          echo "| SCIP Property | Value |"
          echo "|----------|-------|"
          echo "| Repository | \`$upload_repo\` |"
          echo "| Commit | [\`${upload_commit:0:12}\`](${SRC_ENDPOINT}/${upload_repo}/-/commit/${upload_commit}) |"
          [ -n "$upload_root" ] && [ "$upload_root" != "null" ] && echo "| Root | \`$upload_root\` |"
          echo "| File | \`$upload_file\` |"
          echo "| Indexer | \`$upload_indexer\` |"
          echo "| Version | \`$upload_indexer_version\` |"
          echo ""
          echo "[View processing status]($upload_url)"
        } >> "$GITHUB_STEP_SUMMARY"

        echo "Upload complete"
