---
name: Sourcegraph Go SCIP Indexer
description: Generate SCIP data from Go source code
author: Sourcegraph
branding:
  icon: code
  color: orange

inputs:
  project_root:
    description: Specifies the directory to index
    default: .
  module_root:
    description: Specifies the directory containing the go.mod file
    required: false
  repository_root:
    description: Specifies the top-level directory of the git repository
    required: false
  repository_remote:
    description: Specifies the canonical name of the repository remote
    required: false
  module_name:
    description: Specifies the name of the module defined by module-root
    required: false
  module_version:
    description: Specifies the version of the module defined by module-root
    required: false
  scip_go_version:
    description: Version of scip-go to use (e.g., "v0.1.26", "latest")
    default: "v0.1.26"
  output:
    description: Output file path for the SCIP index
    default: index.scip
  quiet:
    description: Do not output to stdout or stderr
    default: "false"
  verbose:
    description: Verbosity level (0=default, 1=verbose, 2=very verbose, 3=very very verbose)
    default: "0"
  skip_implementations:
    description: Skip generating implementations
    default: "false"
  skip_tests:
    description: Skip compiling tests. Will not generate SCIP indexes over tests.
    default: "false"
  package_patterns:
    description: "Package patterns to index. Default: './...' indexes all packages recursively."
    default: "./..."
  upload:
    description: Upload the index to a Sourcegraph instance
    default: "false"
  sourcegraph_url:
    description: URL of the Sourcegraph instance (e.g., https://sourcegraph.com)
    required: false
  sourcegraph_token:
    description: Sourcegraph access token for uploading indexes
    required: false
  github_token:
    description: GitHub access token with 'public_repo' scope for repository verification when lsif.enforceAuth is enabled
    required: false
  src_cli_version:
    description: Version of src-cli to use for uploads (e.g., "6.12.0", "latest")
    default: "6.12.0"

outputs:
  index_path:
    description: Path to the generated SCIP index file
    value: ${{ steps.scip-go.outputs.index_path }}

runs:
  using: composite
  steps:
    - name: Install scip-go
      shell: bash
      env:
        SCIP_GO_VERSION: ${{ inputs.scip_go_version }}
      run: |
        set -euo pipefail
        echo "Installing scip-go@${SCIP_GO_VERSION}..."
        go install "github.com/sourcegraph/scip-go/cmd/scip-go@${SCIP_GO_VERSION}"
        echo "scip-go installed successfully"
        scip-go --version || true

    - name: Run scip-go
      id: scip-go
      shell: bash
      working-directory: ${{ inputs.project_root }}
      env:
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_MODULE_ROOT: ${{ inputs.module_root }}
        INPUT_REPOSITORY_ROOT: ${{ inputs.repository_root }}
        INPUT_REPOSITORY_REMOTE: ${{ inputs.repository_remote }}
        INPUT_MODULE_NAME: ${{ inputs.module_name }}
        INPUT_MODULE_VERSION: ${{ inputs.module_version }}
        INPUT_QUIET: ${{ inputs.quiet }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
        INPUT_SKIP_IMPLEMENTATIONS: ${{ inputs.skip_implementations }}
        INPUT_SKIP_TESTS: ${{ inputs.skip_tests }}
        INPUT_PACKAGE_PATTERNS: ${{ inputs.package_patterns }}
        INPUT_PROJECT_ROOT: ${{ inputs.project_root }}
      run: |
        set -euo pipefail

        ARGS=()
        if [ -n "$INPUT_OUTPUT" ]; then
          ARGS+=("--output=$INPUT_OUTPUT")
        fi
        if [ -n "$INPUT_MODULE_ROOT" ]; then
          ARGS+=("--module-root=$INPUT_MODULE_ROOT")
        fi
        if [ -n "$INPUT_REPOSITORY_ROOT" ]; then
          ARGS+=("--repository-root=$INPUT_REPOSITORY_ROOT")
        fi
        if [ -n "$INPUT_REPOSITORY_REMOTE" ]; then
          ARGS+=("--repository-remote=$INPUT_REPOSITORY_REMOTE")
        fi
        if [ -n "$INPUT_MODULE_NAME" ]; then
          ARGS+=("--module-name=$INPUT_MODULE_NAME")
        fi
        if [ -n "$INPUT_MODULE_VERSION" ]; then
          ARGS+=("--module-version=$INPUT_MODULE_VERSION")
        fi
        if [ "$INPUT_QUIET" = "true" ]; then
          ARGS+=("--quiet")
        fi
        if [ "$INPUT_VERBOSE" != "0" ]; then
          i=0
          while [ "$i" -lt "$INPUT_VERBOSE" ]; do
            ARGS+=("-v")
            i=$((i + 1))
          done
        fi
        if [ "$INPUT_SKIP_IMPLEMENTATIONS" = "true" ]; then
          ARGS+=("--skip-implementations")
        fi
        if [ "$INPUT_SKIP_TESTS" = "true" ]; then
          ARGS+=("--skip-tests")
        fi

        echo "Running: scip-go ${ARGS[*]} $INPUT_PACKAGE_PATTERNS"
        scip-go "${ARGS[@]}" "$INPUT_PACKAGE_PATTERNS"

        if [ -f "$INPUT_OUTPUT" ]; then
          echo "SCIP index generated successfully: $INPUT_OUTPUT"
          {
            echo "index_path<<EOF"
            echo "${INPUT_PROJECT_ROOT}/${INPUT_OUTPUT}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        else
          echo "Error: SCIP index file not found at $INPUT_OUTPUT"
          exit 1
        fi

    - name: Validate upload inputs
      if: inputs.upload == 'true'
      shell: bash
      env:
        SRC_ENDPOINT: ${{ inputs.sourcegraph_url }}
        SRC_ACCESS_TOKEN: ${{ inputs.sourcegraph_token }}
      run: |
        set -euo pipefail
        if [ -z "$SRC_ENDPOINT" ]; then
          echo "Error: sourcegraph_url is required when upload is enabled"
          exit 1
        fi
        if [ -z "$SRC_ACCESS_TOKEN" ]; then
          echo "Error: sourcegraph_token is required when upload is enabled"
          exit 1
        fi

    - name: Install src-cli
      if: inputs.upload == 'true'
      shell: bash
      env:
        SRC_CLI_VERSION: ${{ inputs.src_cli_version }}
      run: |
        set -euo pipefail
        mkdir -p "$HOME/.local/bin"

        case "$(uname -s)-$(uname -m)" in
          Linux-x86_64)  BINARY="src_linux_amd64" ;;
          Linux-aarch64) BINARY="src_linux_arm64" ;;
          Darwin-x86_64) BINARY="src_darwin_amd64" ;;
          Darwin-arm64)  BINARY="src_darwin_arm64" ;;
          *) echo "Error: Unsupported platform $(uname -s)-$(uname -m)"; exit 1 ;;
        esac

        if [ "$SRC_CLI_VERSION" = "latest" ]; then
          echo "Installing latest src-cli ($BINARY)..."
          echo "Warning: Checksum verification not available for 'latest' version"
          curl -fsSL "https://sourcegraph.com/.api/src-cli/$BINARY" -o "$HOME/.local/bin/src"
        else
          echo "Installing src-cli@${SRC_CLI_VERSION} ($BINARY)..."
          RELEASE_URL="https://github.com/sourcegraph/src-cli/releases/download/${SRC_CLI_VERSION}"
          curl -fsSL "${RELEASE_URL}/$BINARY" -o "$HOME/.local/bin/src"

          echo "Verifying checksum..."
          CHECKSUMS_FILE=$(mktemp)
          curl -fsSL "${RELEASE_URL}/src-cli_${SRC_CLI_VERSION}_checksums.txt" -o "$CHECKSUMS_FILE"

          EXPECTED_CHECKSUM=$(grep "  ${BINARY}\$" "$CHECKSUMS_FILE" | awk '{print $1}')
          if [ -z "$EXPECTED_CHECKSUM" ]; then
            echo "Error: Could not find checksum for $BINARY in checksums file"
            rm -f "$CHECKSUMS_FILE"
            exit 1
          fi

          if command -v sha256sum &> /dev/null; then
            ACTUAL_CHECKSUM=$(sha256sum "$HOME/.local/bin/src" | awk '{print $1}')
          else
            ACTUAL_CHECKSUM=$(shasum -a 256 "$HOME/.local/bin/src" | awk '{print $1}')
          fi

          if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
            echo "Error: Checksum verification failed"
            echo "Expected: $EXPECTED_CHECKSUM"
            echo "Actual:   $ACTUAL_CHECKSUM"
            rm -f "$CHECKSUMS_FILE" "$HOME/.local/bin/src"
            exit 1
          fi

          echo "Checksum verified successfully"
          rm -f "$CHECKSUMS_FILE"
        fi
        chmod +x "$HOME/.local/bin/src"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Upload SCIP index
      if: inputs.upload == 'true'
      shell: bash
      working-directory: ${{ inputs.project_root }}
      env:
        SRC_ENDPOINT: ${{ inputs.sourcegraph_url }}
        SRC_ACCESS_TOKEN: ${{ inputs.sourcegraph_token }}
        INPUT_OUTPUT: ${{ inputs.output }}
        INPUT_REPOSITORY_REMOTE: ${{ inputs.repository_remote }}
        INPUT_PROJECT_ROOT: ${{ inputs.project_root }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        set -euo pipefail

        # Mask secrets to prevent accidental exposure in logs
        if [ -n "$SRC_ACCESS_TOKEN" ]; then
          echo "::add-mask::$SRC_ACCESS_TOKEN"
        fi
        if [ -n "$INPUT_GITHUB_TOKEN" ]; then
          echo "::add-mask::$INPUT_GITHUB_TOKEN"
        fi

        # Validate URL to prevent credential exfiltration
        if [[ ! "$SRC_ENDPOINT" =~ ^https:// ]]; then
          echo "Error: sourcegraph_url must use HTTPS"
          exit 1
        fi
        if [[ "$SRC_ENDPOINT" =~ @ ]]; then
          echo "Error: sourcegraph_url must not contain embedded credentials"
          exit 1
        fi

        UPLOAD_ARGS=("-file=$INPUT_OUTPUT" "-no-progress")

        if [ -n "$GITHUB_SHA" ]; then
          UPLOAD_ARGS+=("-commit=$GITHUB_SHA")
        fi

        if [ -n "$INPUT_REPOSITORY_REMOTE" ]; then
          UPLOAD_ARGS+=("-repo=$INPUT_REPOSITORY_REMOTE")
        elif [ -n "$GITHUB_REPOSITORY" ]; then
          UPLOAD_ARGS+=("-repo=github.com/$GITHUB_REPOSITORY")
        fi

        if [ -n "$INPUT_PROJECT_ROOT" ] && [ "$INPUT_PROJECT_ROOT" != "." ]; then
          UPLOAD_ARGS+=("-root=$INPUT_PROJECT_ROOT")
        fi

        if [ -n "$INPUT_GITHUB_TOKEN" ]; then
          UPLOAD_ARGS+=("-github-token=$INPUT_GITHUB_TOKEN")
        fi

        echo "Uploading SCIP index to $SRC_ENDPOINT..."
        echo "Running: src code-intel upload -file=$INPUT_OUTPUT -no-progress [additional flags...]"

        # Disable command tracing to prevent token exposure if set -x is enabled
        { set +x; } 2>/dev/null || true
        src code-intel upload "${UPLOAD_ARGS[@]}"
        upload_status=$?

        # Clear sensitive variables
        unset SRC_ACCESS_TOKEN INPUT_GITHUB_TOKEN

        if [ $upload_status -ne 0 ]; then
          echo "Error: Upload failed"
          exit $upload_status
        fi
        echo "Upload complete"
